services:
  db:
    image: postgres
    build: ./db
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: crypto
      POSTGRES_PASSWORD: cryptonic
      POSTGRES_DB: ohlcvt
      POSTGRES_PORT: 5432
    volumes:
      - ./db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - db_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: mis7er.neo@gmail.com
      PGADMIN_DEFAULT_PASSWORD: cryptonic
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - db_network

  api:
    build: ./API
    ports:
      - "3000:3000"
    environment:
      - WORKERS_PER_CORE=2
      - LOG_LEVEL=debug
    volumes:
      - ./API:/app
    # Commande à exécuter au démarrage du conteneur
    # Cette commande fait plusieurs choses :
    # 1. Change le répertoire courant vers /app
    # 2. Définit PYTHONPATH pour inclure /app
    # 3. Exécute les tests avec pytest
    # 4. Lance l'application avec Gunicorn et Uvicorn

    command: sh -c "cd /app && PYTHONPATH=/app pytest tests && gunicorn -k uvicorn.workers.UvicornWorker -c gunicorn_conf.py app.main:app"
    networks:
      - api_network

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    depends_on:
      - api
      - db
    environment:
      - API_URL=http://api:3000
    networks:
      - api_network
  #
  # webserver:
  #   image: apache/airflow:2.5.1
  #   restart: always
  #   environment:
  #     AIRFLOW__CORE__EXECUTOR: LocalExecutor
  #     AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
  #     AIRFLOW__CORE__FERNET_KEY: 'YOUR_FERNET_KEY'
  #     AIRFLOW__WEBSERVER__SECRET_KEY: 'YOUR_SECRET_KEY'
  #   depends_on:
  #     - db
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - airflow_network

  # scheduler:
  #   image: apache/airflow:2.5.1
  #   restart: always
  #   environment:
  #     AIRFLOW__CORE__EXECUTOR: LocalExecutor
  #     AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
  #     AIRFLOW__CORE__FERNET_KEY: 'YOUR_FERNET_KEY'
  #   depends_on:
  #     - db
  #   networks:
  #     - airflow_network

  # worker:
  #   image: apache/airflow:2.5.1
  #   restart: always
  #   environment:
  #     AIRFLOW__CORE__EXECUTOR: LocalExecutor
  #     AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
  #     AIRFLOW__CORE__FERNET_KEY: 'YOUR_FERNET_KEY'
  #   depends_on:
  #     - db
  #   networks:
  #     - airflow_network

volumes:
  local_pgdata:
  pgadmin-data:


networks:
  db_network:
    driver: bridge
  airflow_network:
    driver: bridge
  api_network:
    driver: bridge
