
route:
  group_by: ['alertname']
  receiver: 'default-receiver'
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h

global:
  smtp_from: 'test.prometheus.datascientest@gmail.com'
  smtp_smarthost: 'smtp.gmail.com:465'   # ou 'smtp.gmail.com:587'
  smtp_auth_username: 'test.prometheus.datascientest@gmail.com'
  smtp_auth_password: 'test_prometheus_datascientest'
  smtp_require_tls: true


receivers:
- name: 'default-receiver'
  email_configs:
    - to: 'test.prometheus.d4tascientest@gmail.com'
    - to: 'fl@belette73.fr' # change this if you want
- name: 'admin'
  email_configs:
  - to: 'test.prometheus.datascientest@gmail.com'


# # alertmanager.yml
# route:
#   group_by: ['alertname']
#   receiver: 'email_notifications'
#   group_wait: 10s
#   group_interval: 5m
#   repeat_interval: 3h

# receivers:
#   - name: 'email_notifications'
#     email_configs:
#       - to: 'your_email@example.com'
#         from: 'alertmanager@example.com'
#         smarthost: 'smtp.example.com:587'
#         auth_username: 'alertmanager'
#         auth_identity: 'alertmanager'
#         auth_password: 'your_password'