groups:
  - name: monitoring_group
    rules:
      - alert: AirflowDown
        expr: up{job="airflow"} == 0
        labels:
          severity: operation
        annotations:
          summary: 'Airflow is down'
      - alert: PrometheusDown
        expr: up{job="prometheus"} == 0
        labels:
          severity: operation
        annotations:
          summary: 'Our Prometheus Server is down'
      - alert: Server_monitorDown
        expr: up{job="server_monitor"} == 0
        labels:
          severity: critical
        annotations:
          summary: 'Node exporter is Down'
      - alert: ModelScoreTooLow
        expr: prediction_api_model_score < 0.96
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Model score is too low"
          description: "The model score has dropped below 0.96"
