#Version 1 : sans Dokerfile

version: '3.8'
services:
  mlflow:
    image: python:3.12.4
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    working_dir: /app
    command: mlflow server --host 0.0.0.0 --port 5000
  train:
    image: python:3.12.4
    volumes:
      - .:/app
    working_dir: /app
    command: python train.py
    depends_on:
      - mlflow

#Version 1 : avec 2 Dokerfile

version: '3.8'
services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - "5000:5000"
    volumes:
      - .:/app
  train:
    build:
      context: .
      dockerfile: Dockerfile.train
    volumes:
      - .:/app
    depends_on:
      - mlflow