name: Deploy to EC2

on:
  push:
    branches:
      - ghaction
  pull_request:
    branches:
      - ghaction

  workflow_dispatch:
    inputs:
      target_ip:
        description: 'Target EC2 IP address'
        required: true
      ec2_user:
        description: 'EC2 Username'
        required: true
      ec2_key:
        description: 'EC2 Private SSH Key'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ github.event.inputs.ec2_key }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Get EC2 User
      id: get-user
      run: echo "::set-output name=user::$(echo ${{ github.event.inputs.ec2_user }})"

    - name: Get target IP
      id: get-ip
      run: echo "::set-output name=ip::$(echo ${{ github.event.inputs.target_ip }})"

    - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          cp /pem/data_enginering_machine.pem ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa

    - name: Connect to Remote VM
        run: ssh -i "~/.ssh/id_rsa/data_enginering_machine.pem" ${{ github.event.inputs.ec2_user }}@${{ github.event.inputs.target_ip }}
  
    - name: Connect to Remote VM and Clone Repo
        run: |
          ssh -i "~/.ssh/id_rsa/data_enginering_machine.pem" ubuntu@${{ steps.get-ip.outputs.ip }} << 'EOF'
            git clone git clone https://github.com/DstMlOpsCrypto/MainCrypto
          EOF     

    - name: Run Airflow-Init
        run: |
          ssh -i "~/.ssh/id_rsa/data_enginering_machine.pem" ${{ github.event.inputs.ec2_user }}@${{ steps.get-ip.outputs.ip }} << 'EOF'
            docker-compose up airflow-init
          EOF

    - name: Pause for 10 seconds
      run: sleep 10

    - name: Run Airflow
        run: |
          ssh -i "~/.ssh/id_rsa/data_enginering_machine.pem" ${{ github.event.inputs.ec2_user }}@${{ steps.get-ip.outputs.ip }} << 'EOF'
            docker-compose up airflow-init
          EOF

