name: Deploy to Dev

on:
  pull_request:
    branches:
      - dev

jobs:
  test_group1:
    name: Test Group 1 (DB + Container)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose python3
          sudo apt-get install python3-pip
          sudo apt-get install python3-psycopg2
          sudo apt-get install python3-pytest
      - name: Launch Group 1
        run: |
          docker-compose -f docker-compose-group1.yml up -d --build
      - name: Wait for DB to be ready
        run: |
          docker-compose -f docker-compose-group1.yml exec -T db \
          sh -c 'while ! pg_isready; do sleep 1; done'
      - name: Run Tests on DB Container
        run: |
          docker-compose -f docker-compose-group1.yml exec -T db \
          sh -c 'cd /app && pytest test/test_db.py  -v' 
      - name: Tear down containers 
        run: |
          docker-compose -f docker-compose-group1.yml down
